config/routes.rb
Disfraces::Application.routes.draw do
  get "resultados/generar"

  get "resultados/ver"
  get "resultados/total_usuarios"

  resources :disfrazs

  get "home/index"

  devise_for :users

  root :to => 'home#index'

end

app/models/disfraz.rb
class Disfraz < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :username

  belongs_to :disfraz

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/disfrazs_controller.rb
class DisfrazsController < ApplicationController
  before_filter :authenticate_user!

  # GET /disfrazs
  # GET /disfrazs.json
  def index
    return if !current_user.admin?
    @disfrazs = Disfraz.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @disfrazs }
    end
  end

  # GET /disfrazs/1
  # GET /disfrazs/1.json
  def show
    return if !current_user.admin?
    @disfraz = Disfraz.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @disfraz }
    end
  end

  # GET /disfrazs/new
  # GET /disfrazs/new.json
  def new
    @disfraz = Disfraz.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @disfraz }
    end
  end

  # GET /disfrazs/1/edit
  def edit
    return if !current_user.admin?
    @disfraz = Disfraz.find(params[:id])
  end

  # POST /disfrazs
  # POST /disfrazs.json
  def create
    if !current_user.admin?
      flash.now[:error] = 'No eres administrador'
      return
    end
    @disfraz = Disfraz.new(params[:disfraz])

    respond_to do |format|
      if @disfraz.save
        format.html { redirect_to @disfraz, notice: 'Disfraz was successfully created.' }
        format.json { render json: @disfraz, status: :created, location: @disfraz }
      else
        format.html { render action: "new" }
        format.json { render json: @disfraz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /disfrazs/1
  # PUT /disfrazs/1.json
  def update
    if !current_user.admin?
      flash.now[:error] = 'No eres administrador'
      return
    end
    @disfraz = Disfraz.find(params[:id])

    respond_to do |format|
      if @disfraz.update_attributes(params[:disfraz])
        format.html { redirect_to @disfraz, notice: 'Disfraz was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @disfraz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disfrazs/1
  # DELETE /disfrazs/1.json
  def destroy
    if !current_user.admin?
      flash.now[:error] = 'No eres administrador'
      return
    end
    @disfraz = Disfraz.find(params[:id])
    @disfraz.destroy

    respond_to do |format|
      format.html { redirect_to disfrazs_url }
      format.json { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/resultados_controller.rb
class ResultadosController < ApplicationController
  before_filter :authenticate_user!
  def generar
    if current_user.admin?
      disfraces = Disfraz.all.sort_by { rand }
      User.all.each do |u|


        u.disfraz = disfraces.pop

        u.save!

        flash.now[:notice] = 'Resultado generados'
      end
    else
      flash.now[:error] = 'No eres administrador'
    end
  end

  def ver
    return if current_user.disfraz.blank?


    @disfraz = Disfraz.find current_user.disfraz
    @otros = @disfraz.users
  end

  def total_usuarios
    @usuarios = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/disfrazs_helper.rb
module DisfrazsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/resultados_helper.rb
module ResultadosHelper
end

app/views/disfrazs/_form.html.erb
<%= form_for(@disfraz) do |f| %>
  <% if @disfraz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@disfraz.errors.count, "error") %> prohibited this disfraz from being saved:</h2>

      <ul>
      <% @disfraz.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/disfrazs/edit.html.erb
<h1>Editing disfraz</h1>

<%= render 'form' %>

<%= link_to 'Show', @disfraz %> |
<%= link_to 'Back', disfrazs_path %>

app/views/disfrazs/index.html.erb
<h1>Lista de disfraces</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @disfrazs.each do |disfraz| %>
  <tr>
    <td><%= disfraz.nombre %></td>
    <td><%= link_to 'Show', disfraz  if current_user.admin? %></td>
    <td><%= link_to 'Edit', edit_disfraz_path(disfraz)  if current_user.admin? %></td>
    <td><%= link_to 'Destroy', disfraz, confirm: 'Are you sure?', method: :delete  if current_user.admin? %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Disfraz', new_disfraz_path if current_user.admin? %>

app/views/disfrazs/new.html.erb
<h1>New disfraz</h1>

<%= render 'form' %>

<%= link_to 'Back', disfrazs_path %>

app/views/disfrazs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @disfraz.nombre %>
</p>


<%= link_to 'Edit', edit_disfraz_path(@disfraz) %> |
<%= link_to 'Back', disfrazs_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_footer.html.haml
%small.copyright
  Copyright &copy; #{Date.today.year}

app/views/layouts/_head.html.haml
%head
  %meta{ :charset => "utf-8" }/

  -#
    Always force latest IE rendering engine (even in intranet) & Chrome Frame
    Remove this if you use the .htaccess
  %meta{ :content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible" }/

  %title
    Disfraces casa rural

  %meta{ :content => "", :name => "description" }/
  %meta{ :content => "", :name => "author" }/

  -# Mobile viewport optimized: j.mp/bplateviewport
  %meta{ :content => "width=device-width, initial-scale=1.0", :name => "viewport" }/

  = stylesheet_link_tag 'application', :media => 'all'

app/views/layouts/_javascripts.html.haml
-# Grab Google CDN's jQuery, with a protocol relative URL
-# Looks for google_api_key first in ENV['GOOGLE_API_KEY'] then in config/google.yml
-# remote_jquery and local_jquery helpers use minified jquery unless Rails.env is development
- if !google_api_key.blank?
  = javascript_include_tag "//www.google.com/jsapi?key=#{google_api_key}"
  :javascript
    google.load(#{ remote_jquery("1.5.1") });
- else
  = javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/#{ local_jquery("1.5.1") }"


-# fall back to local jQuery if necessary
:javascript
  !window.jQuery && document.write(unescape('%3Cscript src="/javascripts/jquery.min.js"%3E%3C/script%3E'))
  
= javascript_include_tag 'rails', 'plugins', 'application', 'jquery.fancybox-1.3.4', 'jquery.jcarousel', 'jquery.tipsy', 'jquery.placeholder', 'jquery.validate.min', 'informa-app'

-# Fix any <img> or .png_bg bg-images. Also, please read goo.gl/mZiyb
/[if lt IE 7 ]
  = javascript_include_tag 'dd_belatedpng.js'
  :javascript
    //DD_belatedPNG.fix('img, .png_bg');
    
-#  Append your own using content_for :javascripts
= yield :javascripts

-# asynchronous google analytics: mathiasbynens.be/notes/async-analytics-snippet
-# Looks for google_account_id first in ENV['GOOGLE_ACCOUNT_ID'] then in config/google.yml
- if !google_account_id.blank?
  :javascript
    var _gaq = [['_setAccount', '#{google_account_id}'], ['_trackPageview']];
    (function(d, t) {
      var g = d.createElement(t),
          s = d.getElementsByTagName(t)[0];
      g.async = true;
      g.src = ('https:' == location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      s.parentNode.insertBefore(g, s);
    })(document, 'script');

app/views/layouts/_navegacion.html.haml
%ul
  %li
    %strong
      %a= current_user.username if user_signed_in?
  %li
    = link_to 'generar resultados', resultados_generar_path if user_signed_in? && current_user.admin?
  %li
    = link_to 'ver resultados', resultados_ver_path
  %li
    = link_to 'ver usuarios', resultados_total_usuarios_path
  %li
    = link_to 'ver disfraces posibles', disfrazs_path if user_signed_in? && current_user.admin?
  %li.logout
    - if user_signed_in?
      = link_to "Salir", destroy_user_session_path, :method => :delete
    - else
      = link_to "Entrar", new_user_session_path

app/views/layouts/application.html.haml
!!! 5
%html
  = render :partial => 'layouts/head'
  %body
    #nav
      #menu
        = render :partial => 'layouts/navegacion'
    #main
      - if flash.present?
        .flash
          - flash.each do |type, message|
            %div{:class => "message #{type}"}
              %p= message
      #cuerpo
        = yield
      #sidebar
        = yield :sidebar

    %footer#footer
      = render :partial => 'layouts/footer'
  -# All JavaScript at the bottom, except for Modernizr which enables HTML5 elements & feature detects
  = javascript_include_tag "application"
  = csrf_meta_tag

app/views/layouts/notificaciones.html.haml
!!! 5
%html
  %body
    #main
      #cuerpo_nota
        = yield

app/views/resultados/total_usuarios.html.haml
%h1 Lista de usuarios

%table
  - @usuarios.each do |u|
    %tr
      %td
        = u.username

app/views/resultados/ver.html.haml
%h1
  Disfraz --------->
  = @disfraz.nombre if @disfraz.present?

%h2 lo lleva:
%table
  - if @otros.present?
    - @otros.each do |u|
      %tr
        %td
          = u.username